name: Fast Forward Composite Action
description: Fast forward the target branch from a pull request.
author: Lunei Solei
inputs:
  github_token:
    description: The GitHub token for this action to use.
    required: true
  auto_merge:
    description: >
      Boolean that determines if the target branch should be automatically
      fast forwarded after determining that a pull request is eligible to do so.
    default: false
  comment:
    description: >
      "always" - Posts a comment to the pull request indicating whether
      it is possible to fast-forward the target branch, and, if merge 
      is true, whether fast forwarding succeeded.

      "on-error" - A comment is only posted if an error occurs.

      "never" - No comment is posted. The comment is still available 
      via the comment output variable and in the step's summary.
    default: on-error
  merge_command:
    description: >
      The command that a user must put in their comment on a pull request to 
      invoke the bot on that pull request.
    default: /fastforward

outputs:
  comment:
    description: > 
      A comment explaining whether fast forwarding is possible, and, 
      if `merge` is true, whether it was successful. The comment is 
      a JSON document with a single field called `body`.
    value: "${{ steps.fast-forward.outputs.comment }}"

runs:
  using: composite
  steps:
    - id: prechecks
      shell: bash
      env: 
        DEBUG: ${{ inputs.debug }}
        COMMENT: ${{ inputs.comment }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AUTO_MERGE: ${{ inputs.auto_merge }}
      run: "${{ github.action_path }}/scripts/prechecks.sh"
    - id: get-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: "${{ github.action_path }}/scripts/get-pr.sh"
    - id: verify-state
      shell: bash
      env:
        AUTO_MERGE: ${{ inputs.auto_merge }}
        BASE_REF: ${{ steps.get-pr.outputs.base-ref }}
        BASE_SHA: ${{ steps.get-pr.outputs.base-sha }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        HEAD_REF: ${{ steps.get-pr.outputs.head-ref }}
        HEAD_SHA: ${{ steps.get-pr.outputs.head-sha }}
      run: "${{ github.action_path }}/scripts/verify-state.sh"
    - id: perform-merge
      shell: bash
      env:
        HAS_PERMS: ${{ steps.check-perms.outputs.has-perms }}
        IS_POSSIBLE: ${{ steps.check-is-possible.outputs.is-possible }}
      run:
      
    - id: fast-forward
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        COMMENT: ${{ inputs.comment }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AUTO_MERGE: ${{ inputs.auto_merge }}
        BASE_REF: ${{ steps.get-pr.outputs.base-ref }}
        BASE_SHA: ${{ steps.get-pr.outputs.base-sha }}
        HEAD_REF: ${{ steps.get-pr.outputs.head-ref }}
        HEAD_SHA: ${{ steps.get-pr.outputs.head-sha }}
      run: "${{ github.action_path }}/scripts/fast-forward.sh"
