name: Fast Forward Composite Action
description: Fast forward the target branch from a pull request.
author: Lunei Solei
inputs:
  github_token:
    description: The GitHub token for this action to use.
    required: true
  auto_merge:
    description: >
      Boolean that determines the target branch should be automatically
      fast forwarded after determining that a pull request is eligible to do so.
    default: false
  comment:
    description: >
      "always" - Posts a comment to the pull request indicating whether
      it is possible to fast-forward the target branch, and, if merge 
      is true, whether fast forwarding succeeded.

      "on-error" - A comment is only posted if an error occurs.

      "never" - No comment is posted. The comment is still available 
      via the comment output variable and in the step's summary.
    default: on-error
  debug:
    description: If set to true, increases the workflow's verbosity. This may also execute some additional RPCs, and so should normally be disabled.
    default: 0

outputs:
  comment:
    description: > 
      A comment explaining whether fast forwarding is possible, and, 
      if `merge` is true, whether it was successful. The comment is 
      a JSON document with a single field called `body`.
    value: "${{ steps.fast-forward.outputs.comment }}"

runs:
  using: composite
  steps:
    - id: prechecks
      shell: bash
      env: 
        DEBUG: ${{ inputs.debug }}
        COMMENT: ${{ inputs.comment }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AUTO_MERGE: ${{ inputs.auto_merge }}
      run: "${{ github.action_path }}/scripts/prechecks.sh"
    - id: get-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: "${{ github.action_path }}/scripts/get-pr.sh"
    - id: has-perms
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: "${{ github.action_path }}/scripts/has-perms.sh"
      
    - id: fast-forward
      shell: bash
      env:
        DEBUG: ${{ inputs.debug }}
        COMMENT: ${{ inputs.comment }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AUTO_MERGE: ${{ inputs.auto_merge }}
        BASE_REF: ${{ steps.get-pr.outputs.base-ref }}
        BASE_SHA: ${{ steps.get-pr.outputs.base-sha }}
        HEAD_REF: ${{ steps.get-pr.outputs.head-ref }}
        HEAD_SHA: ${{ steps.get-pr.outputs.head-sha }}
      run: "${{ github.action_path }}/scripts/fast-forward.sh"
